### PR TITLE
Fix memory leak in require cache module (fixes #2)

### LINKED ISSUE #2: Memory leak
This module creates memory leak. Simple test case scenario is:

```
const heapdump = require('heapdump');
const requireUncached = require('require-uncached');

let i, m1, m2;

for (i = 0; i < 100000; i++) {
  m1 = require('./module.js');
  m1();
}

heapdump.writeSnapshot('./before-' + Date.now() + '.heapsnapshot');

for (i=0; i < 100000; i++) {
  m2 = requireUncached('./module.js');
  m2();
}

heapdump.writeSnapshot('./after-' + Date.now() + '.heapsnapshot');
```

More information can be found here https://github.com/nodejs/node/issues/8443. 

I can PR this, but I am not sure how to handle this correctly.

### PR DESCRIPTION
**Pull request by adammockor**
Hello,

this PR is an attempt to fix memory leak with require described in issue #2.

Please let me now if it is ok and merge-able.

Thank you.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -9,10 +9,19 @@ module.exports = function (moduleId) {
 	}
 
 	var filePath = resolveFrom(path.dirname(callerPath()), moduleId);
-	var tmp = require.cache[filePath];
+	
+	// delete itselft from module parent
```
Comment (sindresorhus) [inline index.js]: typo

File: index.js [hunk 2]
```diff
@@ -9,10 +9,19 @@ module.exports = function (moduleId) {
...
+	if (require.cache[filePath].parent) {
+		var i = require.cache[filePath].parent.children.length;
+		while (i--) {
+		  if (require.cache[filePath].parent.children[i].id === filePath) {
+				require.cache[filePath].parent.children.splice(i, 1);
+			}
+		}
+	}
+	// delete module form cache
```
Comment (sindresorhus) [inline index.js]: typo

File: index.js [hunk 3]
```diff
@@ -9,10 +9,19 @@ module.exports = function (moduleId) {
 	}
 
 	var filePath = resolveFrom(path.dirname(callerPath()), moduleId);
-	var tmp = require.cache[filePath];
+	
+	// delete itselft from module parent
+	if (require.cache[filePath].parent) {
+		var i = require.cache[filePath].parent.children.length;
+		while (i--) {
+		  if (require.cache[filePath].parent.children[i].id === filePath) {
```
Comment (sindresorhus) [inline index.js]: Follow the existing indentation.

**Comment by adammockor** [comment]
Thank you for your feedback.

More information about my problem can be found https://github.com/eslint/eslint/issues/7109.

I am using your test to confirm functionality and I also used eslint tests suite to confirm functionality in larger project.

Should I write dedicated test to test contents of `require.cache` module?

**Comment by sindresorhus** [comment]
Ideally, there needs to be a test that confirms the memory like and so to prevent future regressions.

**Comment by adammockor** [comment]
Prevent future regressions is hard think to do, because this module relies on unofficial require API, so it can be changed anytime. There is no official way of doing this (https://github.com/nodejs/node/issues/8443#issuecomment-247384217).

There is a way of testing memory heap diffs via https://github.com/marcominetti/node-memwatch, but I rather don't do this, because these kind of modules are really not stable to use programatically in different environments  (I am currently unable to install it on node 6.5.0 and I have issues with this at past).

So there is working your end-to-end test. 

I can create test to check if `require.cache` supports parent child relationship and inspect cache for module availability.

I don't have any more ideas, what more can be done :)

**Comment by sindresorhus** [comment]
> Prevent future regressions is hard think to do, because this module relies on unofficial require API, so it can be changed anytime.

No, [the `module` system is locked](https://nodejs.org/api/modules.html#modules_modules). It won't ever change.

> I don't have any more ideas, what more can be done :)

Add a file that can be manually run that visibly leaks memory, so I can manually confirm. I need proof that your change actually fixes it ;)

**Comment by adammockor** [comment]
I prepared gist. https://gist.github.com/adammockor/fbc2919e3fa4f4ba7ae62b09cda4e08f

**Comment by sindresorhus** [comment]
@adammockor Can you include it in this PR? I'd like to be able to run it on any new changes.

**Comment by sindresorhus** [comment]
ping :)

**Comment by adammockor** [comment]
Sorry for the delay. I include heapdump test as you wished, but io.js test is falling due to compatibility issues with heapdump module. Should I exclude heapdump from devDependecies?

File: package.json [hunk 4]
```diff
@@ -32,6 +33,7 @@
     "resolve-from": "^1.0.0"
   },
   "devDependencies": {
-    "ava": "0.0.3"
+    "ava": "0.0.3",
+    "heapdump": "~0.3.7"
```
Comment (sindresorhus) [inline package.json]: `~` => `^`

**Comment by sindresorhus** [comment]
> but io.js test is falling due to compatibility issues with heapdump module

Should be fixed in master. Rebase.

-

Seems you forgot to actually include the file.

**Comment by sindresorhus** [comment]
You also need to fix the merge conflict.

File: test-memory.js [hunk 5]
```diff
@@ -0,0 +1,14 @@
+const heapdump = require('heapdump');
+const uncached = require('./index.js');
+
+for (let i = 0; i < 100000; i++) {
+  require('./fixture.js')();
```
Comment (SamVerschueren) [inline test-memory.js]: Indentation should happen with tabs. Files should also end in a newline. If you're not using it already, I suggest installing the `EditorConfig` plugin for your text editor ;).

File: package.json [hunk 6]
```diff
@@ -33,7 +33,13 @@
...
   },
   "devDependencies": {
-    "ava": "0.0.3",
+    "ava": "*",
+    "xo": "^0.16.0",
     "heapdump": "^0.3.7"
+  },
+  "xo": {
+    "rules": {
+      "import/no-dynamic-require": "off"
```
Comment (SamVerschueren) [inline package.json]: It's best practice to disable rules on a per line basis instead of globally by adding `// eslint-disable-line import/no-dynamic-require` after the `heapdump.writeSnapshot` line.

Comment (sindresorhus) [inline package.json]: @SamVerschueren I added that there. Mostly because I had to turn it off both in the code and tests, so was better placed there.

**Comment by sindresorhus** [comment]
Thank you @adammockor :)

**Comment by adammockor** [comment]
Thank you for your time and patience.

File: package.json (hunk 6 above)
Comment (SamVerschueren) [inline package.json]: 👍
